-- Active: 1788351675293@@127.0.0.1@3306@smartcoffee_dml_ana
--DROP DATABASE IF EXISTS SMARTCOFFEE_DML_ANA;

CREATE DATABASE SMARTCOFFEE_DML_ANA;

USE SMARTCOFFEE_DML_ANA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONE VARCHAR(20),
    CIDADE VARCHAR(60) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    -- CONSTRAINT: SIGNIFICA UMA RESTRIÇÃO E DECLARAÇÃO DE CHAVE ESTRANGEIRA
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS ENUM('ABERTO','REPARANDO','FINALIZADO','CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(150),
    CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO)
        REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO(
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PAGAMENTO_FORMA FOREIGN KEY (ID_FORMA_PAGAMENTO)
        REFERENCES FORMA_PAGAMENTO (ID_FORMA_PAGAMENTO)
);

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CIDADE,ATIVO) VALUES
('BRUNO SOUZA','BRUNO@EMAIL.COM','199999901','LIMEIRA', TRUE),
('ANA SILVA','ANA@EMAIL.COM','199999902','LIMEIRA', TRUE),
('CARLA MENDES','CARLA@EMAIL.COM',NULL,'PIRACICABA', TRUE),
('DIEGO SANTOS','DIEGO@EMAIL.COM','199999904','AMERICANA', TRUE),
('ELISA ROCHA','ELISA@EMAIL.COM',NULL,'SÃO-PAULO', TRUE),
('FELIPE LIMA','FELIPE@EMAIL.COM','199999906','CAMPINAS', TRUE),
('GABRIELA ALVES','GABRIELA@EMAIL.COM','199999907','LIMEIRA', TRUE),
('HENRIQUE COSTA','HENRIQUR@EMAIL.COM',NULL,'JÁU', TRUE),
('ISABELLI MARTINS','ISABELLI@EMAIL.COM','199999909','LIMEIRA', TRUE),
('JOÃO PEREIRA','JOÃO@EMAIL.COM','199999910','LIMEIRA', TRUE);

INSERT INTO CATEGORIA (NOME) VALUES
('CAFÉS'),('BEBIDAS'),('COMBOS'),('DOCES'),('SALGADOS');

SELECT * FROM cliente; 

INSERT INTO PRODUTO (NOME,PRECO,ATIVO,ID_CATEGORIA) VALUES
('CAFÉ ESPRESSO', 7.00, TRUE,1),('CAFÉ DUPLO',10.00,TRUE,1),
('CAFÉ COM LEITE', 9.50, TRUE,1),('CAPPUCINO',13.00,TRUE,1),
('MOCHA CHOCOLATE', 15.50, TRUE,1),('COLD BREW',14.00,TRUE,2),
('FRAPPÉ DE CHOCOLATE', 18.00, TRUE,2),('SUCO DE LARANJA',10.00,TRUE,2),
('BROWNIE', 9.00, TRUE,3),('CHEESECAKE',14.50,TRUE,3),
('COOKIE DE CHOCOLATE', 7.50, TRUE,3),('PÃO DE QUIEJO',6.50,TRUE,4),
('CROISSANT', 12.00, TRUE,4),('SANDUÍCHE NATURAL',16.00,TRUE,4),
('COMBO CAFÉ + PÃO DE QUEIJO', 12.50, TRUE,5),('COMBO CAPPUCINO + BROWNIE',20.00,TRUE,5);

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS, VALOR_TOTAL, ID_CLIENTE) VALUES
('2026-09-01 O8:15:00','FINALIZADO',16.00,1),
('2026-09-01 O9:30:00','FINALIZADO',26.00,2),
('2026-09-01 1O:20:00','CANCELADO',18.00,3),
(NOW(), 'ABERTO',0.00, 8);

SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

INSERT INTO item_pedido (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(1,1,1,7.00,NULL),(1,9,1,9.00,NULL),(2,4,2,13.00,'SEM ')

